paths:
  static: static
  uploads: static/uploads
timezone: Europe/Madrid

markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: true # <--- CAMBIADO A TRUE para habilitar las tablas
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true

_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram

# ----------------------------------------------------
# DEFINICIÓN DE SHORTCODES CUSTOM (Añade esta sección)
# ----------------------------------------------------
_snippets:
  # Shortcode de la tabla bilingüe / corporativa
  tabla:
    template: hugo_paired_snippet
    inline: false
    preview:
      text: "Tabla de datos"
      icon: table_chart
    definitions:
      shortcode: "tabla"
      attributes:
        named:
          - name: "caption"
            type: "string"
            label: "Pie de tabla / Leyenda"

  # Shortcode de figuras e imágenes
  figura:
    template: hugo_snippet
    inline: false
    preview:
      text: "Figura"
      icon: image
    definitions:
      shortcode: "figura"
      attributes:
        named:
          - name: "src"
            type: "image"
            label: "Imagen"
          - name: "caption"
            type: "string"
            label: "Pie de figura"
          - name: "alt"
            type: "string"
            label: "Texto alternativo"

collections_config:
  content:
    path: content
    icon: wysiwyg
  themes_mi_tema_archetypes:
    path: themes/mi-tema/archetypes
    icon: home_iot_device
  themes_mi_tema_content:
    path: themes/mi-tema/content
    icon: sentiment_content
  themes_mi_tema_layouts:
    path: themes/mi-tema/layouts
    icon: responsive_layout
